-- 建立 PRODUCER_STATUS table
CREATE TABLE IF NOT EXISTS RETAIL_LAB.RAW.PRODUCER_STATUS (
  EVENT_ID      STRING,
  PRODUCER_ID   NUMBER,
  CUSTOMER_ID   NUMBER,
  NEW_STATUS    STRING,
  STATUS_TS     TIMESTAMP_NTZ,
  SOURCE        STRING
);

-- 建立 ORDER_STATUS_EVENTS table
CREATE TABLE IF NOT EXISTS RETAIL_LAB.RAW.ORDER_STATUS_EVENTS (
  EVENT_ID      STRING,
  ORDER_ID      NUMBER,
  CUSTOMER_ID   NUMBER,
  NEW_STATUS    STRING,
  STATUS_TS     TIMESTAMP_NTZ,
  SOURCE        STRING
);
--- CREATE WAREHOUSE FOR THE CLASS ---
CREATE WAREHOUSE IF NOT EXISTS TEACH_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create you database on snowflake
CREATE DATABASE IF NOT EXISTS RETAIL_LAB;

--Create you schema 
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.STG;
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.DWH;

--- CREATE WAREHOUSE FOR THE CLASS ---
CREATE WAREHOUSE IF NOT EXISTS TEACH_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create you database on snowflake
CREATE DATABASE IF NOT EXISTS RETAIL_LAB;

--Create you schema 
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.STG;
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.DWH;
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.RAW;

USE WAREHOUSE TEACH_WH;          -- choose the compute engine
USE DATABASE RETAIL_LAB;         -- choose where data lives
USE SCHEMA RAW;  
-- choose sub-folder in database
CREATE TABLE IF NOT EXISTS RETAIL_LAB.RAW.ORDER_STATUS_EVENTS (
  EVENT_ID      STRING,
  ORDER_ID      NUMBER,
  CUSTOMER_ID   NUMBER,
  NEW_STATUS    STRING,
  STATUS_TS     TIMESTAMP_NTZ,
  SOURCE        STRING
);
USE WAREHOUSE TEACH_WH;          -- choose the compute engine
USE DATABASE RETAIL_LAB;         -- choose where data lives
USE SCHEMA RAW;  
-- choose sub-folder in database
CREATE TABLE IF NOT EXISTS RETAIL_LAB.RAW.PRODUCER_STATUS (
  EVENT_ID      STRING,
  PRODUCER_ID   NUMBER,
  CUSTOMER_ID   NUMBER,
  NEW_STATUS    STRING,
  STATUS_TS     TIMESTAMP_NTZ,
  SOURCE        STRING
);
USE WAREHOUSE TEACH_WH;          -- choose the compute engine
USE DATABASE RETAIL_LAB;         -- choose where data lives
USE SCHEMA RAW;  
-- choose sub-folder in database
CREATE TABLE IF NOT EXISTS RETAIL_LAB.RAW.CUSTOMER (
  NAME          STRING,
  EMAIL         VARCHAR,
  CUSTOMER_ID   NUMBER,
  CREATED_AT    TIMESTAMP_NTZ
);