--- CREATE WAREHOUSE FOR THE CLASS ---
CREATE WAREHOUSE IF NOT EXISTS TEACH_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create you database on snowflake
CREATE DATABASE IF NOT EXISTS RETAIL_LAB;

--Create you schema 
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.STG;
CREATE SCHEMA IF NOT EXISTS RETAIL_LAB.DWH;